### PR TITLE
app init and implementations

### PR DESCRIPTION
**Pull request by YannickZahinda**
In this branch I created
 
- `Created an API endpoint that selects a random greeting from my table `
- `Created a static view that will be the root of your app`
- `Initialized your project with Git`
- `Added the jsbundling-rails gem into my GemFile`
- `Installed needed node dependencies as described in the previous lesson's tutorial`

### CODE REVIEW

**Comment by rloterh** [comment]
Hi Zahinda, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that needs to follow these multiple initial steps in order for our project to meet criteria for review:
- [ ] Your project has incorrect gitflow/ GitHub flow. Kindly note that the merge request for this activity should be **from feature into development**. Kindly use the correct gitflow.
- [ ] `node_modules` directory included in the project structure. Kindly ensure to exclude this directory from uploading to the repository by including the directory in the `.gitignore` file.
- [ ] Linter checks are not showing on your Pull Request. Kindly ensure that **all* required linters are properly configured with regards to GitHub actions, and **all** checks are passing.
- [ ] Your project does not have an appropriate ReadMe. Kindly ensure that your ReadMe is detailed and reflects your project. I suggest you use this [recommended template](https://github.com/microverseinc/readme-template/blob/master/README.md). Kindly request another review when this fix is done.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @YannickZahinda 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that:
- [ ]  You have submitted a project that does not follow proper gitflow, Kindly use the correct gitflow.
- [ ] You have submitted a project that has node modules committed to git, please fix it 👍🏿 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by FrederickMih** [comment]
Hi @YannickZahinda, you haven't yet fixed all the above issues mentioned above :point_up:  Can we share them together?

**Comment by YannickZahinda** [comment]
Hey @FrederickMih , The previous reviewer asked me about adding node_modules into gitignore, I did it and using the correct git flow I also did, I'm not sure to get well the suggested changes.
Can you clarify for me ?

**Comment by FrederickMih** [comment]
> Hey @FrederickMih , The previous reviewer asked me about adding node_modules into gitignore, I did it and using the correct git flow I also did, I'm not sure to get well the suggested changes. Can you clarify for me ?

Great let's go on Zoom

**Pull request closed without merging**
